
name = "Piezo (Buzzer)"
manufacturer = "Arduino"
is_main_board = false
required_crates = ["embedded-hal", "embedded-time", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

# Each element of the Pinout Vec should be prefaced with [[pinout]]
[[pinout]]
pins = ["input", "gnd"]
interface = { iface_type = "I2C", direction = "Bidirectional" }
