name = "LCD_Example"
location = "example-code/lcd_screen"
current_view = "BoardsView"

[system]
discrete_components = []
connections = []

[system.main_board]
name = "Feather RP2040"
manufacturer = "Adafruit"
board_type = "Main"
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[system.main_board.pinout]]
pins = ["rx", "tx"]

[system.main_board.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.main_board.pinout]]
pins = ["scl", "sda"]

[system.main_board.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[system.main_board.pinout]]
pins = ["mosi", "miso", "sclk"]

[system.main_board.pinout.interface]
iface_type = "SPI"
direction = "Output"

[[system.peripheral_boards]]
name = "OLED Featherwing (128x64)"
manufacturer = "Adafruit"
board_type = "Peripheral"
standard = "Feather"
bsp = "iron-coder-featherwing-oled-bsp"
related_crates = ["sh1107"]

[[system.peripheral_boards.pinout]]
pins = ["8", "9"]

[system.peripheral_boards.pinout.interface]
iface_type = "I2C"
direction = "Input"
