name = "Testing"
location = "example-code/blink_leds"
current_view = "FileTree"

[system]
connections = []

[system.main_board]
name = "MicroMod RP2040"
manufacturer = "Sparkfun"
is_main_board = true
standard = "MicroMod"
cpu = "Cortex-M0"
ram = 264
flash = 8000
required_crates = ["sparkfun_micromod_rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]

[[system.main_board.pinout]]
pins = ["rx", "tx"]

[system.main_board.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.main_board.pinout]]
pins = ["scl", "sda"]

[system.main_board.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[system.main_board.pinout]]
pins = ["mosi", "miso", "sclk"]

[system.main_board.pinout.interface]
iface_type = "SPI"
direction = "Output"

[[system.peripheral_boards]]
name = "OLED Featherwing (128x64)"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-oled-bsp"
related_crates = ["sh1107"]

[[system.peripheral_boards.pinout]]
pins = ["8", "9"]

[system.peripheral_boards.pinout.interface]
iface_type = "I2C"
direction = "Input"
