
name = "Yellow LED"
manufacturer = "Adafruit"
is_main_board = false
required_crates = ["embedded-hal", "embedded-time", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

bsp = "iron-coder-yellow-led-bsp"

# Each element of the Pinout Vec should be prefaced with [[pinout]]
[[pinout]]
pins = ["cathode", "anode"]
interface = { iface_type = "I2C", direction = "Bidirectional" }
