name = "LEDArray"
location = "example-code/led_array"
current_view = "FileTree"

[system]
discrete_components = []
connections = []

[system.main_board]
name = "Feather RP2040"
manufacturer = "Adafruit"
board_type = "Main"
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[system.main_board.pinout]]
pins = ["rx", "tx"]

[system.main_board.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.main_board.pinout]]
pins = ["scl", "sda"]

[system.main_board.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[system.main_board.pinout]]
pins = ["mosi", "miso", "sclk"]

[system.main_board.pinout.interface]
iface_type = "SPI"
direction = "Output"

[[system.peripheral_boards]]
name = "NeoPixel 8x8"
manufacturer = "Adafruit"
board_type = "Peripheral"
bsp = "iron-coder-neopixel-bsp"
related_crates = ["ili9341", "embedded-graphics"]

[[system.peripheral_boards.pinout]]
pins = ["din", "5V", "gnd"]

[system.peripheral_boards.pinout.interface]
iface_type = "NONE"
direction = "Input"

[[system.peripheral_boards.pinout]]
pins = ["gnd", "5V", "dout"]

[system.peripheral_boards.pinout.interface]
iface_type = "NONE"
direction = "Output"
